/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cursoemvideo.supercalculadora;

/**
 *
 * @author alice
 */
public class TelaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() {
        initComponents();
        txtResto.setVisible(false);
        valResto.setVisible(false);
        txtCubo.setVisible(false);
        valCubo.setVisible(false);
        txtRaizQ.setVisible(false);
        valRaizQ.setVisible(false);
        txtRaizC.setVisible(false);
        valRaizC.setVisible(false);
        txtAbs.setVisible(false);
        valAbs.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        valNum = new javax.swing.JSpinner();
        btnCalc = new javax.swing.JButton();
        txtResto = new javax.swing.JLabel();
        txtCubo = new javax.swing.JLabel();
        txtRaizQ = new javax.swing.JLabel();
        txtRaizC = new javax.swing.JLabel();
        txtAbs = new javax.swing.JLabel();
        valResto = new javax.swing.JLabel();
        valCubo = new javax.swing.JLabel();
        valRaizQ = new javax.swing.JLabel();
        valRaizC = new javax.swing.JLabel();
        valAbs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("Super Calculadora");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Informe um valor:");

        valNum.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        valNum.setModel(new javax.swing.SpinnerNumberModel(1, -50, 50, 1));

        btnCalc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCalc.setText("Calcular");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        txtResto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtResto.setText("Resto da divisão por 2:");

        txtCubo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCubo.setText("Elevado ao cubo:");

        txtRaizQ.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtRaizQ.setText("Raiz quadrada:");

        txtRaizC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtRaizC.setText("Raiz cúbica");

        txtAbs.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtAbs.setText("Valor absoluto:");

        valResto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        valResto.setForeground(new java.awt.Color(0, 0, 255));
        valResto.setText("0");

        valCubo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        valCubo.setForeground(new java.awt.Color(0, 0, 255));
        valCubo.setText("0");

        valRaizQ.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        valRaizQ.setForeground(new java.awt.Color(0, 0, 255));
        valRaizQ.setText("0");

        valRaizC.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        valRaizC.setForeground(new java.awt.Color(0, 0, 255));
        valRaizC.setText("0");

        valAbs.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        valAbs.setForeground(new java.awt.Color(0, 0, 255));
        valAbs.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtResto)
                            .addComponent(txtCubo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRaizQ, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRaizC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAbs, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valRaizC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valAbs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valResto, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valCubo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valRaizQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(valNum, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCalc)))
                        .addGap(83, 83, 83)))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(valNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalc))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResto)
                    .addComponent(valResto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCubo)
                    .addComponent(valCubo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRaizQ)
                    .addComponent(valRaizQ))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRaizC)
                    .addComponent(valRaizC))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAbs)
                    .addComponent(valAbs))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        //pega o valor selecionado no spinner
        int valor = Integer.parseInt(valNum.getValue().toString()); 
        
        //resto da divisão por 2
        int resto = valor % 2; 
        txtResto.setVisible(true);
        valResto.setVisible(true);
        valResto.setText(Integer.toString(resto));
        
        //elevado ao cubo
        float cubo = (float) Math.pow(valor, 3);
        txtCubo.setVisible(true);
        valCubo.setVisible(true);
        valCubo.setText(String.format("%.2f", cubo));
        
        //raiz quadrada
        float raizQ = (float) Math.sqrt(valor);
        txtRaizQ.setVisible(true);
        valRaizQ.setVisible(true);
        valRaizQ.setText(String.format("%.2f", raizQ));
        
        //raiz cúbica
        float raizC = (float) Math.cbrt(valor);
        txtRaizC.setVisible(true);
        valRaizC.setVisible(true);
        valRaizC.setText(String.format("%.2f", raizC));
        
        //valor absoluto
        int abs = Math.abs(valor);
        txtAbs.setVisible(true);
        valAbs.setVisible(true);
        valAbs.setText(Integer.toString(abs));
        
    }//GEN-LAST:event_btnCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtAbs;
    private javax.swing.JLabel txtCubo;
    private javax.swing.JLabel txtRaizC;
    private javax.swing.JLabel txtRaizQ;
    private javax.swing.JLabel txtResto;
    private javax.swing.JLabel valAbs;
    private javax.swing.JLabel valCubo;
    private javax.swing.JSpinner valNum;
    private javax.swing.JLabel valRaizC;
    private javax.swing.JLabel valRaizQ;
    private javax.swing.JLabel valResto;
    // End of variables declaration//GEN-END:variables
}
