/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofatorial;

/**
 *
 * @author alice
 */
public class telaFatorial extends javax.swing.JFrame {

    /**
     * Creates new form telaFatorial
     */
    public telaFatorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numFat = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        resFat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCalc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numFat.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        numFat.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));
        numFat.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numFatStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("! =");

        resFat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        resFat.setForeground(new java.awt.Color(255, 0, 51));
        resFat.setText("1");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setText("Calculadora de Fatorial");

        lblCalc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCalc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(numFat, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(resFat, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel3)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numFat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(resFat))
                .addGap(46, 46, 46)
                .addComponent(lblCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numFatStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numFatStateChanged
        int num = (int) numFat.getValue(); //pegar o valor do spinner
        int r = 1; //armazenar o resultado, começa em 1 pq o fatorial de 0 é 1
        int aux = num; //preservar o valor do númeor na variável auxiliar para us[a-lo na impressãp do cálculo
        
        //cálculo do fatorial
        while(num >= 1){ //repete enquanto o número for maior ou igual a 1
            r *= num; //multiplica o valor armazenado em resultado pelo valor do número
            num--; //decrementa o número a cada repetição
        } 
        resFat.setText(Integer.toString(r)); //após o loop, imprime o resultado
        
        //impressão do cálculo
        String calc = ""; //a string começa vazia
        if(aux > 1){ //se o número for maior que 1, existe um cálculoe e ele será apresentado pelo loop
            while(aux > 1){ //enquanto for maior que 1, adiciona o valor do número e o símbolo de multiplicação em calc
                calc += aux + " * ";
                aux--; //decrementa o valor do número
            }
            calc += 1; //quando terminar, adiciona o 1 sozinho, já que não terá mais o símbolo de multiplicação depois dele
            lblCalc.setText(calc); //imprimir a string completa
        } else{ //se o número for 0 ou 1, não é feotp um cálculo
            calc = "1"; //só imprime o 1 mesmo
            lblCalc.setText(calc); //imprimir a string completa
        }
        
    }//GEN-LAST:event_numFatStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaFatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaFatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaFatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaFatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaFatorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCalc;
    private javax.swing.JSpinner numFat;
    private javax.swing.JLabel resFat;
    // End of variables declaration//GEN-END:variables
}
